### ISSUE TITLE
0.0.18 NPM is broken

### ISSUE THREAD

**Issue by worthy7** [nhnent/tui.ngx-calendar#3]
The files look completely different between 17 and 18
0.0.17
![image](https://user-images.githubusercontent.com/4762399/42790455-0900ba18-89a6-11e8-9ee4-da9a571f2428.png)

0.0.18
![image](https://user-images.githubusercontent.com/4762399/42790465-222c8774-89a6-11e8-87d8-3a52a476dfc1.png)

In angular it cannot see the module anymore:
![image](https://user-images.githubusercontent.com/4762399/42790472-32ac7474-89a6-11e8-970c-4716d24e62b4.png)

Is this a problem with how it has been NPM packaged?

**Comment by worthy7** [comment]
@brnrds Any idea? Thanks

**Comment by worthy7** [comment]
Add me as an npm collaborator please worthy7

**Comment by vindiezel23** [comment]
ngx-tui-calendar-defaults.services.ts is missing from the Typescript compilation.

**Comment by worthy7** [comment]
Npm is now fixed. Please upgrade @vindiezel23
